# Default values for did.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

resolvers:
  btcr:
    name: btcr
    image:
      repository: universalresolver/driver-did-btcr
      tag: latest
      imagePullPolicy: IfNotPresent
    environment:
  sov:
    name: sov
    image:
      repository: universalresolver/driver-did-sov
      tag: latest
      imagePullPolicy: IfNotPresent
    environment:
  uport:
    name: uport
    image:
      repository: uport/uni-resolver-driver-did-uport
      tag: latest
      imagePullPolicy: IfNotPresent
    environment:
  stack:
    name: stack
    image:
      repository: universalresolver/driver-did-stack
      tag: latest
      imagePullPolicy: IfNotPresent
    environment:
  erc725:
    name: erc725
    image:
      repository: universalresolver/driver-did-erc725
      tag: latest
      imagePullPolicy: IfNotPresent
    environment:
  dom:
    name: dom
    image:
      repository: universalresolver/driver-did-dom
      tag: latest
      imagePullPolicy: IfNotPresent
    environment:
  dns:
    name: dns
    image:
      repository: universalresolver/driver-dns
      tag: latest
      imagePullPolicy: IfNotPresent
    environment:
  jolo:
    name: jolo
    image:
      repository: jolocomgmbh/jolocom-did-driver
      tag: latest
      imagePullPolicy: IfNotPresent
    environment:
  hacera:
    name: hacera
    image:
      repository: hacera/hacera-did-driver
      tag: latest
      imagePullPolicy: IfNotPresent
    environment:
  web:
    name: web
    image:
      repository: universalresolver/uni-resolver-web
      tag: latest
      imagePullPolicy: IfNotPresent
    mountCustomConfig: true
    environment:
  factom:
    name: factom
    image:
      repository: factominc/driver-did-factom
      tag: latest
      imagePullPolicy: Always
    environment:
      - name: uniresolver_driver_did_factom_factomConnection
        value: harmony
      - name: uniresolver_driver_did_factom_rpcUrlMainnet
        value: https://api.factomd.net
      - name: uniresolver_driver_did_factom_rpcUrlTestnet
        value: https://dev.factomd.net
      - name: uniresolver_driver_did_factom_tfaExplorerApiUrlMainnet
        value: https://explorer.factoid.org/api/v1
      - name: uniresolver_driver_did_factom_tfaExplorerApiUrlTestnet
        value: https://testnet.factoid.org/api/v1
      - name: uniresolver_driver_did_factom_harmonyApiUrl
        value: http://harmony-identity.connect/v1
      - name: uniresolver_driver_did_factom_harmonyApiAppId
        value:
      - name: uniresolver_driver_did_factom_harmonyApiAppKey
        value:
      - name: uniresolver_driver_did_factom_harmonyApiCachingEnabled
        value: true
    volumes:
