apiVersion: apps/v1
kind: Deployment
metadata:
  name: uni-registrar-web
  namespace: did
  labels:
    app: uni-registrar
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uni-registrar-web
  template:
    metadata:
      labels:
        app: uni-registrar-web
    spec:
      containers:
      - name: uni-registrar-web
        image: identitydotcom/uni-registrar-web
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: uni-registrar-web
spec:
  type: NodePort
  selector:
    app: uni-registrar-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
