name: Nightly did-test-suite

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  driver-health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
          caCertificate: ${{ secrets.VAULTCA }}
          secrets: |
            ci/data/gh-workflows/deployment-status slack-webhook-url | SLACK_WEBHOOK_URL
      - name: Get driver status
        uses: ./ci/get-driver-status
        with:
          host: https://dev.uniresolver.io
          out: /home/runner/work/universal-resolver/universal-resolver/driver-status-reports
          keep_result: true
#       - name: Run did-test-suite
#         uses: ./ci/run-did-test-suite
#         with:
#           host: https://did-test-suite.uniresolver.io/test-suite-manager/generate-report
#           driver_status_report: ${{ env.driver_status_report }}
#           reports_folder: ${{ env.reports_folder }}
      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
        if: failure()
