name: Maven and Docker release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Major, Minor or Patch release'
        type: choice
        required: true
        default: 'minor'
        options:
          - "major"
          - "minor"
          - "patch"

jobs:
  maven-release:
    uses: danubetech/workflows/.github/workflows/maven-release.yml@main
    with:
      MAVEN_REPO_SERVER_ID: 'danubetech-maven-releases'
      RELEASE_TYPE: ${{ github.event.inputs.release_type }}
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      CI_SECRET_READER_PERIODIC_TOKEN: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
      VAULTCA: ${{ secrets.VAULTCA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  docker-release:
    needs: maven-release
    uses: danubetech/workflows/.github/workflows/maven-triggered-docker-release.yml@main
    with:
      GLOBAL_IMAGE_NAME: universalresolver/uni-resolver-web
      GLOBAL_REPO_NAME: docker.io
      GLOBAL_FRAMEWORK: triggered
      PATH_TO_DOCKERFILE: uni-resolver-web/docker/Dockerfile
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      CI_SECRET_READER_PERIODIC_TOKEN: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
      VAULTCA: ${{ secrets.VAULTCA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  docker-release-multi-arch:
    needs: docker-release
    uses: decentralized-identity/universal-registrar/.github/workflows/docker-multi-arch.yml@main
    with:
      GLOBAL_FRAMEWORK: maven
      GLOBAL_IMAGE_NAME: universalresolver/uni-resolver-web
      GLOBAL_REPO_NAME: docker.io
      IS_RELEASE: true
      PATH_TO_DOCKERFILE: uni-resolver-web/docker/Dockerfile
      RELEASE_TYPE: ${{ github.event.inputs.release_type }}
    secrets:
      CI_SECRET_READER_PERIODIC_TOKEN: ${{ secrets.CI_SECRET_READER_PERIODIC_TOKEN }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULTCA: ${{ secrets.VAULTCA }}
